In [6]:
import numpy as np
import pandas as pd
import string 
import nltk

from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [7]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\um834\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [12]:
df = pd.read_csv("D:\Project\ML Projects\spam-email-detector\data\spam_email_dataset_1000.csv" , encoding="latin-1")
# df.head()

df.shape

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\um834\AppData\Local\Temp\ipykernel_10620\1102413499.py:1: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("D:\Project\ML Projects\spam-email-detector\data\spam_email_dataset_1000.csv" , encoding="latin-1")

(1000, 2)

In [13]:
df.info

<bound method DataFrame.info of     label                                            message
0     ham  Hi Usman, can we meet tomorrow at 6 PM to disc...
1    spam  Win cash today! Text WIN to 1158 and get enter...
2    spam  Limited time offer! Get 70% off on premium mem...
3     ham  The client requested a few changes in the desi...
4     ham  Happy birthday Bilal! Hope you have a great da...
..    ...                                                ...
995  spam  You have been nominated for a cash prize. Repl...
996  spam  Win cash today! Text WIN to 1187 and get enter...
997   ham  Reminder: our class presentation is scheduled ...
998  spam  Win cash today! Text WIN to 6597 and get enter...
999   ham  Thanks for your help today. I will send the up...

[1000 rows x 2 columns]>

In [14]:
df["label"].value_counts()

label
ham     500
spam    500
Name: count, dtype: int64

In [15]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [16]:
def clean_text(text):
    text = text.lower()

    text = "".join(
        char for char in text
        if char not in string.punctuation
    )

    words = text.split()

    words = [
        word for word in words
        if word not in stopwords.words("english")
    ]

    return " ".join(words)

In [18]:
df["clean_messsage"] = df["message"].apply(clean_text)

df.head()

,label,message,clean_messsage
0,ham,"Hi Usman, can we meet tomorrow at 6 PM to disc...",hi usman meet tomorrow 6 pm discuss project ch...
1,spam,Win cash today! Text WIN to 1158 and get enter...,win cash today text win 1158 get entered grand...
2,spam,Limited time offer! Get 70% off on premium mem...,limited time offer get 70 premium membership a...
3,ham,The client requested a few changes in the desi...,client requested changes design explain call t...
4,ham,Happy birthday Bilal! Hope you have a great da...,happy birthday bilal hope great day check inbo...

In [19]:
df["label_num"] = df["label"].map({"ham": 0, "spam": 1})
df.head()

,label,message,clean_messsage,label_num
0,ham,"Hi Usman, can we meet tomorrow at 6 PM to disc...",hi usman meet tomorrow 6 pm discuss project ch...,0
1,spam,Win cash today! Text WIN to 1158 and get enter...,win cash today text win 1158 get entered grand...,1
2,spam,Limited time offer! Get 70% off on premium mem...,limited time offer get 70 premium membership a...,1
3,ham,The client requested a few changes in the desi...,client requested changes design explain call t...,0
4,ham,Happy birthday Bilal! Hope you have a great da...,happy birthday bilal hope great day check inbo...,0

In [20]:
X = df["clean_messsage"]
y = df["label_num"]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [77]:
vectrizer = TfidfVectorizer()
X_train_vect = vectrizer.fit_transform(X_train)
X_test_vect = vectrizer.transform(X_test)

df.head()

,label,message,clean_messsage,label_num
0,ham,"Hi Usman, can we meet tomorrow at 6 PM to disc...",hi usman meet tomorrow 6 pm discuss project ch...,0
1,spam,Win cash today! Text WIN to 1158 and get enter...,win cash today text win 1158 get entered grand...,1
2,spam,Limited time offer! Get 70% off on premium mem...,limited time offer get 70 premium membership a...,1
3,ham,The client requested a few changes in the desi...,client requested changes design explain call t...,0
4,ham,Happy birthday Bilal! Hope you have a great da...,happy birthday bilal hope great day check inbo...,0

In [78]:
model = MultinomialNB()
model.fit(X_train_vect, y_train)

MultinomialNB()

In [79]:
y_pred = model.predict(X_test_vect)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        99
           1       1.00      1.00      1.00       101

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

In [26]:
confusion_matrix(y_test, y_pred)

array([[ 99,   0],
       [  0, 101]])

In [52]:
def predict_email(message):
    cleaned = clean_text(message)
    vectorized = vectrizer.transform([cleaned])
    prediction = model.predict(vectorized)[0]

    if prediction == 1:
        return "Spam"
    else:
        return "Not Spam"

In [59]:
predict_email("Hi, are we still meeting tomorrow?")

'Not Spam'

In [60]:
predict_email("Hi, are we still meeting tomorrow?")

'Not Spam'

In [61]:
predict_email("Let's have lunch together at 1 PM.")

'Not Spam'

In [62]:
predict_email("Your interview is scheduled for Monday.")

'Not Spam'

In [63]:
predict_email("Can you review the code changes?")

'Not Spam'

In [64]:
predict_email("Congratulations! You have won $1000 cash prize.")

'Spam'

In [65]:
predict_email("Claim your free gift card now.")

'Spam'

In [66]:
predict_email("You are selected as a lucky winner. Click here.")

'Spam'

In [67]:
predict_email("Earn money fast working from home.")

'Spam'

In [68]:
predict_email("Free lunch tomorrow at the office.")

'Not Spam'

In [69]:
predict_email("Meeting winner announcement today.")

'Spam'

In [70]:
predict_email("Your bank account has been suspended. Verify now.")

'Spam'

In [71]:
predict_email("Project offer discussion tomorrow.")

'Not Spam'

In [80]:
import joblib 

joblib.dump(model, "../models/spam_model.pkl")
joblib.dump(vectorizer, "../models/vectorizer.pkl")

print("Model and vectorizer saved successfully.")

Model and vectorizer saved successfully.

In [ ]:
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

vectorizer = TfidfVectorizer()

X_train_vectorized = vectorizer.fit_transform(X_train)

model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

joblib.dump(model, "../models/spam_model.pkl")
joblib.dump(vectorizer, "../models/vectorizer.pkl")